name: Usetheform CI

on: [push, pull_request]

jobs:

  tests:
    name: Unit Tests + Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Run tests 🧪
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'
      - run: npm ci
      - run: npm run test:cov

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Build 🔨
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'
      - run: npm ci
      - run: npm run build --if-present

  deploy_docs:
    name: Deploy Docs
    runs-on: ubuntu-latest
    needs: [tests, build]
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Build Docs 🔨
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'
      - run: npm ci
      - run: npm run docz:build --if-present
      - run: rm .gitignore

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.4.0
        with:
          folder: .docz/dist # The folder the action should deploy.
     